name: recettes_app
description: "A Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Plugins principaux
  url_launcher: ^6.1.10
  share_plus: ^7.0.2   
  cached_network_image: ^3.4.1

  # State management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # UI & icônes
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1

  # Auth providers
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  sign_in_with_apple: ^7.0.1
  local_auth: ^2.1.3

  # Local storage & utilitaires
  shared_preferences: ^2.2.2
  characters: ^1.4.0
  http: ^1.2.1
  meta: ^1.12.0

  # Localisation
  flutter_localizations:
    sdk: flutter

  # Splash screen
  flutter_native_splash: ^2.4.6
 
  # Icône application
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  

flutter:
  uses-material-design: true
  assets:
    - assets/lang/fr.json
    - assets/lang/ar.json
    - assets/lang/en.json
    - assets/images/logo.png
    - assets/images/logo_Aceuil.png
    - assets/images/google_logo.png
    - assets/recipes.json
    - assets/data/recettes_a_to_z.json

#  Icône application
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/AppIcons/playstore.png"
  image_path_ios: "assets/AppIcons/appstore.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#fcfbf5" 

#  Splash screen
flutter_native_splash:
  color: "#fcfbf5"
  image: assets/images/logo.png
  color_dark: "#0F1115"
  image_dark: assets/images/logo.png
  android: true
  ios: true
  android_12:
    image: assets/images/logo.png
    image_dark: assets/images/logo.png
    icon_background_color: "#fcfbf5"
    icon_background_color_dark: "#0F1115"
